#ifndef ENMARCO_H_
#define ENMARCO_H_

/*************************************************************

普通坐标:Normal axis
百分比坐标:Percent axis
对数坐标:Logarithm axis
今日强势品种:Most advanced stocks
今日强势品种:Most declined stocks


详细的 detailed
简单的 simple

大福证券港股行情报价系统:TaiFook Securities Analysis System
  
*************************************************************/

/*************************************************************

  基本名词

*************************************************************/

#ifndef EN_VERSION

	#define _Format_Text_File	"格式文本文件"
	#define _Excel_File			"Excel文件"
	#define _Graphics_File		"图形文件"
	#define _Individual_Kind	"个别类型"
	#define _Cancel_Download	"取消下载"
	#define _Start_Download		"开始下载"
	#define _New_Block			"新建板块"
	#define _Edit_Block			"板块改名"
	#define _Add_Host			"添加主站"
	#define _Edit_Host 			"修改主站"
	#define _Add_Text 			"添加文字"
	#define _Edit_Text 			"编辑文字"
	#define _Add_To_Block 		"加入到板块"
	#define _Refresh_Data 		"刷新数据"
	#define _Construct_Template "开始设置版面"
	#define _Exit_Construct		"退出设置版面"
	#define _Name				"名称"
	#define _Description		"说明"
	#define _BlockName			"板块名:"
	#define _User_Selected		"自选品种"
	#define _User_Selected2		"自选"
	#define _Condition_Block	"条件板块"
	#define _News_TXTColor		"资料和资讯文本"
	#define _FuncTree_TXTColor	"功能树文本"
	#define _Axis				"坐标"
	#define _Big_Title			"大标题"
	#define _Graph_Word			"图形文字"
	#define _Volume				"成交量"
	#define _HighLight_BKColor	"高亮背景色"
	#define _US_Line			"美国线"
	#define _DrawLine_ToolBox	"画线工具"
	#define _UpLine				"阳线"
	#define _DownLine			"阴线"
	#define _FlatLine			"平线"
	#define _Quote_Analyser		"行情浏览"
	#define _Analysis_Graph		"分析图"
	#define _Custom_Template	"定制版面"
	#define _News_Info			"新闻资讯"
	#define _Time				"时间"
	#define _OCVol				"增仓"
	#define _OCString			"性质"
	#define _Data				"数值"
	#define _Start_Time			"开始于"
	#define _End_Time			"结束于"
	#define _Price				"价格"
	#define _Average			"均价"
	#define _NowIncVol			"增仓"
	#define _Classicfied		"分类品种"
	#define _User_Block			"用户板块"
	#define _User_Block2		"自定"
	#define _Volume				"成交量"
	#define _Ratio				"比例"
	#define _Buy_Ratio			"竞买率"
	#define _Day_Line			"日线"
	#define _Week_Line			"周线"
	#define _Month_Line			"月线"
	#define _X_Minute			"分钟"
	#define _1_Minute			"1分钟"
	#define _5_Minutes			"5分钟"
	#define _15_Minutes			"15分钟"
	#define _30_Minutes			"30分钟"
	#define _60_Minutes			"60分钟"
	#define _Multi_Day_Line		"多日线"
	#define _Multi_Minutes		"多分钟"
	#define _Per_Minute			"分时"
	#define _HS_Index			"恒生指数"
	#define _HSZH_Index			"恒生综合"
	#define _HSGQ_Index			"恒生国企"
	#define _Scope_Stat			"区间统计"
	#define _100M				"亿"
	#define _10K				"万"
	#define _100K				"十万"
	#define _10G				"百亿"
	#define _10M				"千万"
	#define _Overlap_stock		"叠加品种"
	#define _Detailed_tick		"成交明细"
	#define _Price_List			"分价表"
	#define _Per_Minute_List	"每分钟成交"
	#define _Immediate_Analysis "分时走势图"
	#define _correlative_data	"相关数值"
	#define _Bid_Broker_Queue	"买家经纪排位"
	#define _Ask_Broker_Queue	"卖家经纪排位"
	#define _BA_Ratio			"委比"
	#define _BA_Diff			"委差"
	#define _Contract_Diff		"仓差"
	#define _Contract			"持仓"
	#define _OpenContract		"开仓"
	#define _CloseContract		"平仓"
	#define _LongOpen			"多开"
	#define _LongClose			"多平"
	#define _ShortOpen			"空开"
	#define _ShortClose			"空平"
	#define _Settle				"结算"
	#define _Prev_Settle		"昨结"
	#define _Yield				"收益率"
	#define _IEP				"参考价"
	#define _IEV				"参考量"
	#define _MrkCap				"市值"
	#define _PreMinum			"溢价"
	#define _Gearing			"贡杆比率"
	#define _ExecPrice			"行使价"
	#define _ConvRatio			"换购比率"
	#define _InterRate			"利息"
	#define _SYL				"市盈率"
	#define _ZXL				"周息率"
	#define _PX					"派息"
	#define _YL					"盈利"

	#define _Code			"代码"
	#define _HYCode			"合约号"
	#define _PZName			"品种名"
	#define _Bid			"买入"
	#define _Ask			"卖出"
	#define _Volume			"成交量"
	#define _Turnover		"成交额"
	#define _Nominal		"现价"
	#define _New			"最新"
	#define _Change			"涨跌"
	#define _Change_Ratio	"涨幅"
	#define _Prev_Close		"前收"
	#define _Open			"今开"
	#define _High			"最高"
	#define _Low			"最低"
	#define _Total_Volume	"总量"
	#define _Total_Amount	"总额"
	#define _Cur_Volume		"现量"
	#define _Market			"市场"
	#define _PE_Ratio		"市盈"
	#define _Year_High		"年高"
	#define _Year_Low		"年低"
	#define _Lot_Size		"单位"
	#define _Currency		"币种"
	#define _Swing			"振幅"
	#define _Tick_Diff		"笔涨跌"
	#define _VOL_COMPRA		"量比"
	#define _Inside			"内盘"
	#define _Outside		"外盘"
	#define _InOut			"内外比"
	#define _Spread			"买卖差价"
	#define _Expire_Date	"到期日"
	#define _Aver_Price		"均价"
#ifdef BIG5
	#define _Ask_1			"卖一"
	#define _Ask_2			"卖二"
	#define _Ask_3			"卖三"
	#define _Ask_4			"卖四"
	#define _Ask_5			"卖五"
	#define _Bid_1			"买一"
	#define _Bid_2			"买二"
	#define _Bid_3			"买三"
	#define _Bid_4			"买四"
	#define _Bid_5			"买五"
#else
	#define _Ask_1			"卖①"
	#define _Ask_2			"卖②"
	#define _Ask_3			"卖③"
	#define _Ask_4			"卖④"
	#define _Ask_5			"卖⑤"
	#define _Bid_1			"买①"
	#define _Bid_2			"买②"
	#define _Bid_3			"买③"
	#define _Bid_4			"买④"
	#define _Bid_5			"买⑤"
#endif
	#define _Ask_VOL		"卖量"
	#define _Bid_VOL		"买量"
	#define _SCOPE			"区段"
	#define _AllHq_Info		"开:%s 高:%s 收:%s 低:%s 量:%s 额:%s 幅:%s 振:%s 换:%s"
	#define _PreDelta		"昨虚"
	#define _NowDelta		"虚实"

	#define _MISC_KIND		"综合类型"
	#define _AB_KIND		"国内股票"
	#define _HK_KIND		"香港股票"
	#define _FREMD_KIND		"国外股票"
	#define _FORE_KIND		"外汇"
	#define _FUTURE_KIND	"期货"
	#define _INDEX_KIND		"国际指数"

	#define _T_SYSTEM		"(系统)"
	#define _System_Cfg		"系统设置"
	#define _Block_Cfg		"用户板块设置"
#else

	#define _Format_Text_File	"Format Text File"
	#define _Excel_File			"Excel File"
	#define _Graphics_File		"Graphics File"
	#define _Individual_Kind	"Individual Kind"
	#define _Cancel_Download	"Cancel"
	#define _Start_Download		"Download"
	#define _New_Block			"New Block"
	#define _Edit_Block			"Edit Block"
	#define _Add_Host			"Add Host"
	#define _Edit_Host 			"Edit Host"
	#define _Add_Text 			"Add Text"
	#define _Edit_Text 			"Edit Text"
	#define _Add_To_Block 		"Add To Block"
	#define _Refresh_Data 		"Refresh Data"
	#define _Construct_Template "Construct Template"
	#define _Exit_Construct		"Exit Construction"
	#define _Name				"Name"
	#define _Description		"Description"
	#define _BlockName			"BlockName"
	#define _User_Selected		"User Selected"
	#define _User_Selected2		"UserSel"
	#define _Condition_Block	"Condition BLK"
	#define _News_TXTColor		"News Info"
	#define _FuncTree_TXTColor	"FuncTree"
	#define _Axis				"Axis"
	#define _Big_Title			"BigTitle"
	#define _Graph_Word			"GraphTXT"
	#define _Volume				"Volume"
	#define _HighLight_BKColor	"HighLight BKColor"
	#define _US_Line			"US Line"
	#define _DrawLine_ToolBox	"DrawLine"
	#define _UpLine				"Up"
	#define _DownLine			"Down"
	#define _FlatLine			"Flat"
	#define _Quote_Analyser		"Quote Analyser"
	#define _Analysis_Graph		"Analysis Graph"
	#define _Custom_Template	"Custom Template"
	#define _News_Info			"News & Info"
	#define _Time				"Time"
	#define _OCVol				"O-C"
	#define _OCString			"Description"
	#define _Data				"Data"
	#define _Start_Time			"Start Time"
	#define _End_Time			"End Time"
	#define _Price				"Price"
	#define _Average			"Average"
	#define _NowIncVol			"Increace VolInStock"
	#define _Classicfied		"Classicfied"
	#define _User_Block			"User BLK"
	#define _User_Block2		"UserBLK"
	#define _Volume				"Volume"
	#define _Ratio				"Ratio"
	#define _Buy_Ratio			"Buy Ratio"
	#define _Day_Line			"Day"
	#define _Week_Line			"Week"
	#define _Month_Line			"Month"
	#define _X_Minute			"Minute"
	#define _1_Minute			"1 Min"
	#define _5_Minutes			"5 Min"
	#define _15_Minutes			"15 Min"
	#define _30_Minutes			"30 Min"
	#define _60_Minutes			"60 Min"
	#define _Multi_Day_Line		"N Day"
	#define _Multi_Minutes		"N Min"
	#define _Per_Minute			"Per Minute"

	#define _HS_Index			"HSI"
	#define _HSZH_Index			"HSCI"
	#define _HSGQ_Index			"HSCE"
	#define _Scope_Stat			"Scope Stat"
	#define _100M				"*100M"
	#define _10K				"*10K"
	#define _100K				"*100K"
	#define _10G				"*10G"
	#define _10M				"*10M"
	#define _Overlap_stock		"Overlap stock"
	#define _Detailed_tick		"Detailed Tick"
	#define _Price_List			"Price List"
	#define _Per_Minute_List	"Per Minute List"
	#define _Immediate_Analysis "Immediate Analysis"
	#define _correlative_data	"Correlative Data"
	#define _Bid_Broker_Queue	"Bid Broker Queue"
	#define _Ask_Broker_Queue	"Ask Broker Queue"
	#define _BA_Ratio			"B/A Ratio"
	#define _BA_Diff			"B/A Diff"
	#define _Contract_Diff		"Contract Diff"
	#define _Contract			"Contract"
	#define _OpenContract		"OpenContr"
	#define _CloseContract		"CloseContr"
	#define _LongOpen			"Long(Open)"
	#define _LongClose			"Long(Close)"
	#define _ShortOpen			"Short(Open)"
	#define _ShortClose			"Short(Close)"
	#define _Settle				"Settle"
	#define _Prev_Settle		"PrevSett"
	#define _Yield				"Yield"
	#define _IEP				"IEP"
	#define _IEV				"IEV"
	#define _MrkCap				"MrkCap"
	#define _PreMinum			"PreMinum"
	#define _Gearing			"Gearing"
	#define _ExecPrice			"ExecPrice"
	#define _ConvRatio			"ConvRatio"

	#define _Code			"Code"
	#define _HYCode			"Code"
	#define _PZName			"StockName"
	#define _Bid			"Bid"
	#define _Ask			"Ask"
	#define _Volume			"Volume"
	#define _Turnover		"Turnover"
	#define _Nominal		"Nominal"
	#define _New			"New"
	#define _Change			"Change"
	#define _Change_Ratio	"Range"
	#define _Prev_Close		"PrevClo"
	#define _Open			"Open"
	#define _High			"High"
	#define _Low			"Low"
	#define _Total_Volume	"Volume"
	#define _Total_Amount	"Amount"
	#define _Cur_Volume		"CurVol"
	#define _Market			"Market"
	#define _PE_Ratio		"P/E"
	#define _Year_High		"YearHigh"
	#define _Year_Low		"YearLow"
	#define _Lot_Size		"Lot Size"
	#define _Currency		"Currency"
	#define _Swing			"Swing"
	#define _Tick_Diff		"TickDiff"
	#define _VOL_COMPRA		"VolumeRatio"
	#define _Inside			"Inside"
	#define _Outside		"Outside"
	#define _InOut			"In/Out"
	#define _Spread			"Spread"
	#define _Expire_Date	"ExpireDate"
	#define _Aver_Price		"AverPrice"
	#define _Ask_1			"A1"
	#define _Ask_2			"A2"
	#define _Ask_3			"A3"
	#define _Ask_4			"A4"
	#define _Ask_5			"A5"
	#define _Bid_1			"B1"
	#define _Bid_2			"B2"
	#define _Bid_3			"B3"
	#define _Bid_4			"B4"
	#define _Bid_5			"B5"
	#define _Ask_VOL		"AskVol"
	#define _Bid_VOL		"BidVol"
	#define _SCOPE			"Scope"
	#define _AllHq_Info		"Open:%s High:%s Close:%s Low:%s Volume:%s Amount:%s Range:%s Swing:%s VolRatio:%s"

	#define _MISC_KIND		"Misc"
	#define _AB_KIND		"AB Stock"
	#define _HK_KIND		"HK Stock"
	#define _FREMD_KIND		"Fremd Stock"
	#define _FORE_KIND		"Foreign"
	#define _FUTURE_KIND	"Future"
	#define _INDEX_KIND		"Index"

	#define _T_SYSTEM		"(System)"
	#define _System_Cfg		"Option"
	#define _Block_Cfg		"Block configuraion"
#endif

/*************************************************************

  句子

*************************************************************/


#ifndef EN_VERSION
	#define IDS_STR_1  "请输入交易委托程序的路径:"
	#define IDS_STR_2  "定制版面文件"
	#define IDS_STR_3  "点击此处连接行情主站"
	#define IDS_STR_4  "选择叠加的品种"
	#define IDS_STR_5  "选择基准品种"
	#define IDS_STR_6  "仅单选，可用键盘精灵选择"
	#define IDS_STR_7  "不能打开板块文件!"
	#define IDS_STR_8  "不能存取板块配置文件!"
	#define IDS_STR_9  "不能将板块配置文件存盘!"
	#define IDS_STR_10 "存在同名的板块!"
	#define IDS_STR_11 "存在同名的板块简称!"
	#define IDS_STR_12 "板块改名错误"
	#define IDS_STR_13 "不能创建板块文件!"
	#define IDS_STR_14 "您确定删除该板块吗?"
	#define IDS_STR_15 "板块删除错误!"
	#define IDS_STR_16 "您确定删除该板块中的全部品种吗?"
	#define IDS_STR_17 "导出板块成功!"
	#define IDS_STR_18 "导出失败!请检查文件路径和权限"
	#define IDS_STR_19  "不能删除当前正在使用的方案!"
	#define IDS_STR_20  "您确定删除此方案吗?"
	#define IDS_STR_21  "仅仅行情、报表和分析版面能导出文本数据?"
	#define IDS_STR_22  "导出成功!请查看相应的文件!"
	#define IDS_STR_23  "不要再乱折腾啦！受不了啦！"
	#define IDS_STR_24  "提示:新建版面时,请点右键进行操作!"
	#define IDS_STR_25  "您确定删除当前版面吗?"
	#define IDS_STR_26  "初始化数据没有取得,不能运行!"
	#define IDS_STR_27  "您确定取消下载吗？"
	#define IDS_STR_28  "请输入板块名称!"
	#define IDS_STR_29  "请输入板块简称!建议用英文字母"
	#define IDS_STR_30  "IP地址不能为空!"
	#define IDS_STR_31  "主站名称不能为空!"
	#define IDS_STR_32  "在本地存盘过程中碰到一个问题,\n是否继续?"
	#define IDS_STR_33  "写文件失败,请确定目录是否可写,硬盘空间是否足够!"
	#define IDS_STR_34  "文件打开或创建失败!请确定目录是否可写或是否有防病毒软件干扰!\n是否继续?"
	#define IDS_STR_35  "致命错误,内存不足!"
	#define IDS_STR_36  "您确定退出本系统吗？"
	#define IDS_STR_37  "切换成全屏模式后,按Ctrl+P键恢复到正常模式"
	#define IDS_STR_38  "未知错误，请重新连接!"
	#define IDS_STR_39  "数据初始化错误，程序退出!"
	#define IDS_STR_40  "当前程序已是最新的,不需要升级!"
	#define IDS_STR_41  "请先连接到行情主站!"
	#define IDS_STR_42  "请先定义一些定制版面,才能设置初始版面!"
	#define IDS_STR_43  "工具栏停靠位置需要重新进入系统才能生效!"
	#define IDS_STR_44  "网络环境的设置需要重新进入系统才能生效!"
	#define IDS_STR_45  "您设置的初始版面下次系统进入后才能生效!"
	#define IDS_STR_46  "您已经运行了一个相同类型的行情分析系统,\n如果在相同目录下运行,可能会造成冲突.\n是否继续?"
	#define IDS_STR_47  "公式编译未通过!"
	#define IDS_STR_48  "您要删除所有的画线吗 ?"
	#define IDS_STR_49  "不能再画新的线了!"
	#define IDS_STR_50  "叠加品种的本地K线数据太少,显示可能不准确!"
	#define IDS_STR_51  "是否换成百分比坐标 ?"
	#define IDS_STR_52  "选择的品种与当前品种的开收市时间不一致,不能叠加!"
	#define IDS_STR_53  "在叠加品种时不能画线!"
	#define IDS_STR_54  "您确定从当前板块中删除这些品种吗?"
	#define IDS_STR_56  "欢迎使用"
	#define IDS_STR_57  "正在查找最快的主站..."
	#define IDS_STR_58  "正在连接到主站,请稍等..."
	#define IDS_STR_59  "不能连接到主站!"
	#define IDS_STR_60  "导出板块文件"
	#define IDS_STR_61  "本指标无参数需要设置."
	#define IDS_STR_62  "行情主站名称"
	#define IDS_STR_63  "行情主站地址"
	#define IDS_STR_64  "交易中心名称"
	#define IDS_STR_65  "交易中心地址"
	#define IDS_STR_66  "资讯主站名称"
	#define IDS_STR_67  "资讯主站地址"
	#define IDS_STR_68 "行情连接被断开!"
	#define IDS_STR_69 "您确定恢复到系统缺省设置吗?"
	#define IDS_STR_70  "板块太多，不能再增加!"
	#define IDS_STR_71 "主站太多，不能再增加!"
	#define IDS_STR_72  "配色方案太多，不能再添加!"
	#define IDS_STR_73  "请输入显示字串:"
	#define IDS_STR_74  "显示字串"
	#define IDS_STR_75  "将此配色方案另存为:"
	#define IDS_STR_76  "保存方案"
	#define IDS_STR_77  "通过代理服务器连接..."
	#define IDS_STR_78	"正在验证用户信息..."
	#define IDS_STR_79	"正在登录服务器,请稍等..."
	#define IDS_STR_80  "不能连接到代理服务器!"
	#define IDS_STR_81  "请求行情服务..."
	#define IDS_STR_82  "从服务器端取信息失败!"
	#define IDS_STR_83  "请求品种信息..."
	#define IDS_STR_84  "初始化商业智能平台..."
	#define IDS_STR_85  "连接超时!"
	#define IDS_STR_86  "是否尝试连接另一行情主站:"
	#define IDS_STR_87  "选择定制文件导出目录"
	#define IDS_STR_88	"快捷命令为空，请重新输入!"
	#define IDS_STR_89	"名字有重复，请重新输入!"
	#define IDS_STR_90  "名字为空，请重新输入!"
	#define IDS_STR_91  "快捷命令长度不匹配!格式为.0??"
	#define IDS_STR_92  "快捷命令格式错误!格式为.0??"
	#define IDS_STR_93  "快捷命令数字范围不对!格式为.0??"
	#define IDS_STR_94  "已有版面用此快捷命令"
	#define IDS_STR_95  "导入板块成功!"
	#define IDS_STR_96  "导入失败!请检查文件路径和权限"
	#define IDS_STR_97  "请添加下载的股票!"
	#define IDS_STR_98	"日期选取不合理!"
	#define IDS_STR_99	"下载被取消."
	#define IDS_STR_100  "正在下载日线数据.."
	#define IDS_STR_101  "下载完毕."
	#define IDS_STR_102  "下载失败."
	#define IDS_STR_103  "该用户不存在."
	#define IDS_STR_104  "密码不正确."
	#define IDS_STR_105  "服务器不允许此种类型的客户端连入."
	#define IDS_STR_106  "正在读取数据,请稍等..."
	#define IDS_STR_107  ""
	#define IDS_STR_108	 "无内容."
	#define IDS_STR_109	 "未知错误."
	#define IDS_STR_110  "正在刷新全部行情..."
	#define IDS_STR_111  "正在刷新当前行情..."
	#define IDS_STR_112  "就绪"
	#define IDS_STR_113  "不能创建套接字!"
	#define IDS_STR_114  "代理失败!"
	#define IDS_STR_115  "代理服务器超时!"
	#define IDS_STR_116  "通过代理连接主站不成功!"
	#define IDS_STR_117  "代理Base64编码错误!"
	#define IDS_STR_118	 "发送数据失败!"
	#define IDS_STR_119	 "接收数据失败!"
	#define IDS_STR_120  "处理成功!"
	#define IDS_STR_121  "请选择指标公式"
	#define IDS_STR_122  "请选择主图的指标公式"
	#define IDS_STR_123  "交易系统指示"
	#define IDS_STR_124  "五彩K线指示"
	#define IDS_STR_125  "删除交易系统指示"
	#define IDS_STR_126  "修改交易系统公式"
	#define IDS_STR_127  "删除五彩K线"
	#define IDS_STR_128	 "个股基本资料无法得到!"
	#define IDS_STR_129	 ""

#else
	#define IDS_STR_1   "Please input the path of trading program."
	#define IDS_STR_2   "Custom Template File"
	#define IDS_STR_3   "Click here to connect the host."
	#define IDS_STR_4   "Select overlap stock"
	#define IDS_STR_5   "Select base stock"
	#define IDS_STR_6   "Only single-select,and can select by KeyGuy."
	#define IDS_STR_7   "Cannot open the block file!"
	#define IDS_STR_8   "Cannot access the block configuraion!"
	#define IDS_STR_9   "Cannot save the block configuraion!"
	#define IDS_STR_10  "Exist the same name of the block!"
	#define IDS_STR_11  "Exist the same short name of the block!"
	#define IDS_STR_12  "Fail to change name!"
	#define IDS_STR_13  "Cannot new the block file."
	#define IDS_STR_14  "Are you sure to delete the block?"
	#define IDS_STR_15  "Fail to delete!"
	#define IDS_STR_16  "Are you sure to delete all stocks of the block?"
	#define IDS_STR_17  "Succeed to export the block."
	#define IDS_STR_18  "Fail to export,please check the file path and secure right."
	#define IDS_STR_19  "Cannot delete the current color-solution."
	#define IDS_STR_20  "Are you sure delete the color-solution?"
	#define IDS_STR_21  "Only Quote,Report and Chart can be exported."
	#define IDS_STR_22  "Succeed to export,please check the relevant file."
	#define IDS_STR_23  "I'm busy,want to sleep :)"
	#define IDS_STR_24  "You can click the right mouse button to process the construction."
	#define IDS_STR_25  "Are you sure to delete the current solution?"
	#define IDS_STR_26  "There is no initial data,cannot run with offline"
	#define IDS_STR_27  "Are you sure to cancel download?"
	#define IDS_STR_28  "Please input the name of the block."
	#define IDS_STR_29  "Please input the short name of the block."
	#define IDS_STR_30  "IP Address cannot be empty."
	#define IDS_STR_31  "Host Name cannot be empty."
	#define IDS_STR_32  "Catch a problem when saving file,continue?"
	#define IDS_STR_33  "Fail to write,please check the path or the space of disk."
	#define IDS_STR_34  "Fail to create and open,please check the path or the possible disturbance of Anti-virus programs."
	#define IDS_STR_35  "Fatal error,Not enough memory."
	#define IDS_STR_36  "Are you sure to quit?"
	#define IDS_STR_37  "After switch to fullScreen view,you can resume by pressing Ctrl+P."
	#define IDS_STR_38  "Unknown error,please reconnect."
	#define IDS_STR_39  "Fail to initialize data,System want to quit."
	#define IDS_STR_40  "Current program is newest,don't need to update."
	#define IDS_STR_41  "Please connect with Quote Host."
	#define IDS_STR_42  "Please construct some templates before you set the system template."
	#define IDS_STR_43  "The configuraion of the toolbar cannot go into effect until you restart the program."
	#define IDS_STR_44  "The configuraion of the network cannot go into effect until you restart the program."
	#define IDS_STR_45  "The settings of the system template cannot go into effect until you restart the program."
	#define IDS_STR_46  "You have run the another same program,it may make the conflict,continue?"
	#define IDS_STR_47  "Fail to compile the formula."
	#define IDS_STR_48  "Are you sure to delete all the drawlines?"
	#define IDS_STR_49  "You cannot draw more lines."
	#define IDS_STR_50  "There is no sufficient data of the overlap stock."
	#define IDS_STR_51  "Are you sure to switch to percent axis?"
	#define IDS_STR_52  "The time isn't consistent,cannot overlap."
	#define IDS_STR_53  "Cannot draw line when overlapping."
	#define IDS_STR_54  "Are you sure to delete all the stocks from the current block?"
	#define IDS_STR_56  "Welcome to use "
	#define IDS_STR_57  "Find the fastest host..."
	#define IDS_STR_58  "Connecting the host..."
	#define IDS_STR_59  "Fail to Connect the host."
	#define IDS_STR_60  "Export Block File"
	#define IDS_STR_61  "This Guide needs no Parameters."
	#define IDS_STR_62  "Quote Host Name"
	#define IDS_STR_63  "Quote Host IP"
	#define IDS_STR_64  "Trade Host Name"
	#define IDS_STR_65  "Trade Host IP"
	#define IDS_STR_66  "Info Host Name"
	#define IDS_STR_67  "Info Host IP"
	#define IDS_STR_68  "Disconnected."
	#define IDS_STR_69  "Are you sure to resume the default configuration?"
	#define IDS_STR_70  "Cannot add more blocks."
	#define IDS_STR_71  "Cannot add more hosts."
	#define IDS_STR_72  "Cannot add more color-solutions."
	#define IDS_STR_73  "Input the description:"
	#define IDS_STR_74  "Description"
	#define IDS_STR_75  "Save color-solution as:"
	#define IDS_STR_76  "Save color-solution"
	#define IDS_STR_77  "Connecting the host through proxy..."
	#define IDS_STR_78	"Verifying user information..."
	#define IDS_STR_79	"Connecting the host,please wait.."
	#define IDS_STR_80  "Fail to Connect the proxy."
	#define IDS_STR_81  "Obtaining the service..."
	#define IDS_STR_82  "Fail to access the information"
	#define IDS_STR_83  "Getting the stock information..."
	#define IDS_STR_84  "Initializing the system platform..."
	#define IDS_STR_85  "Time out in connecting!"
	#define IDS_STR_86  "Try another host?"
	#define IDS_STR_87  "Select directory for exporting the Custom Template."
	#define IDS_STR_88	"KeyGuy is empty,please input again!"
	#define IDS_STR_89	"Exist the same name,please input again!"
	#define IDS_STR_90  "Name is empty,please input again!"
	#define IDS_STR_91  "Invalid keyguy length,e.g. .0??"
	#define IDS_STR_92  "Invalid keyGuy,e.g. .0??"
	#define IDS_STR_93  "Invalid keyGuy,e.g. .0??"
	#define IDS_STR_94  "Exist the same KeyGuy in another template."
	#define IDS_STR_95  "Succeed to import the block."
	#define IDS_STR_96  "Fail to import,please check the file path and secure right."
	#define IDS_STR_97  "Please add stocks."
	#define IDS_STR_98	"Invalid date."
	#define IDS_STR_99	"Downloading is canceled."
	#define IDS_STR_100  "Downloading dayline data..."
	#define IDS_STR_101  "Succeed to download."
	#define IDS_STR_102  "Fail to download."
	#define IDS_STR_103  "user isn't found"
	#define IDS_STR_104  "wrong password."
	#define IDS_STR_105  "Invalid client program."
	#define IDS_STR_106  "Accessing data,please wait..."
	#define IDS_STR_107  ""
	#define IDS_STR_108	 "No data."
	#define IDS_STR_109	 "Unknown error."
	#define IDS_STR_110  "Refreshing all data..."
	#define IDS_STR_111  "Refreshing current data..."
	#define IDS_STR_112  "Ready."
	#define IDS_STR_113  "Fail to create socket."
	#define IDS_STR_114  "Proxy failed!"
	#define IDS_STR_115  "Proxy time out!"
	#define IDS_STR_116  "Fail to connect host through proxy!"
	#define IDS_STR_117  "Proxy Base64 coding error!"
	#define IDS_STR_118	 "Fail to send data!"
	#define IDS_STR_119	 "Fail to receive data!"
	#define IDS_STR_120  "Processed successfully!"
	#define IDS_STR_121  "Select Guide"
	#define IDS_STR_122  "Select Guide"
	#define IDS_STR_123  "Select Guide"
	#define IDS_STR_124  "Select Guide"
	#define IDS_STR_125  "Delete Colorful K-Line Guide"
	#define IDS_STR_126  "Change Guide Content"
	#define IDS_STR_127  "Delete Colorful K-Line"
	#define IDS_STR_128	 "The Stock Information Is Unavailable!"
	#define IDS_STR_129	 ""

#endif

#endif
